import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import ToastProvider from "@/providers/ToastProvider";
import { auth } from "./auth";
import AuthProvider from "@/providers/AuthProvider";

// Inter
const inter = localFont({
  src: "./fonts/InterVTF.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700 800 900",
  display: "swap",
  fallback: ["Inter", "system-ui", "sans-serif"],
  style: "normal",
});

// Space Grotesk
const spaceGrotesk = localFont({
  src: "./fonts/SpaceGroteskVTF.ttf",
  variable: "--font-space-grotesk",
  weight: "100 200 300 400 500 600 700 800 900",
  display: "swap",
  fallback: ["Space Grotesk", "system-ui", "sans-serif"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <AuthProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div>{children}</div>
          </ThemeProvider>
          <ToastProvider />
        </AuthProvider>
      </body>
    </html>
  );
}
